version: '3.8'

services:
  # --- Database (Local PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: abaya-db
    restart: always
    environment:
      POSTGRES_USER: abaya_user
      POSTGRES_PASSWORD: abaya_password
      POSTGRES_DB: abaya_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - abaya-network

  # --- Backend Service ---
  backend:
    build: .
    container_name: abaya-backend
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads # Persist gambar di VPS
    networks:
      - abaya-network

  # --- Frontend Service ---
  frontend:
    build: ./frontend
    container_name: abaya-frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - abaya-network

  # --- Nginx Proxy Manager (GUI untuk Manage Domain & SSL) ---
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: always
    ports:
      - '80:80'    # HTTP
      - '81:81'    # Admin Panel GUI
      - '443:443'  # HTTPS
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - abaya-network

networks:
  abaya-network:
    driver: bridge
